// Generated by CoffeeScript 1.9.3
(function() {
  (function() {
    var MYAPP, sum;
    MYAPP = {};
    MYAPP.calculator = {
      'left': null,
      'right': null
    };
    MYAPP.coordinate = {
      'left': null,
      'right': null
    };
    MYAPP.calculator.left = 10;
    MYAPP.calculator.right = 20;
    sum = function() {
      return MYAPP.calculator.left + MYAPP.calculator.right;
    };
    return alert(sum());
  })();

  console.log(MYAPP);

}).call(this);
